axis_linear_x: 1
scale_linear_x: 0.15
scale_linear_x_turbo: 0.5

axis_linear_y: 0
scale_linear_y: 0.15
scale_linear_y_turbo: 0.5

axis_angular_z: 3
scale_angular_z: 0.3
scale_angular_z_turbo: 1

axis_angular_y: 4
scale_angular_y: 0.3
scale_angular_y_turbo: 1

enable_button: 4  #L1
enable_turbo_button: 5  #R1

